version: '3.8'
services:
  telegram-bot-api:
    build: .
    environment:
      - PORT=8081
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_DOMAIN=${WEBHOOK_DOMAIN}
      - LOG_LEVEL=info
    ports:
      - "8081:8081"
